# Dependencies
markdown:         redcarpet
highlighter:      rogue

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Serving
baseurl: '/' # does not include hostname

# Setup
title:            +/- an 1/8th
tagline:          'Sprinter Workvan to Homevan'
description:      'Converting a <a href="https://instagram.com/benthevanman" target="_blank">2004 Sprinter</a> from a working van to a rolling home.'
#url:              http://hyde.getpoole.com

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - pygments

author:
  name:           'Ben Reichert'
  url:            https://instagram.com/benthevanman

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
